---
title: "About This Website"
---

###Hi all! I’m Andrea and I am a senior microbiology major graduating this spring. I am currently a TA for Microbio 312 and an undergraduate research assistant. I am in Dr. Jeff Blanchard’s lab currently studying novel ‘giant' viruses and bacteriophage identified in forest soil using genome-based technologies and bioinformatic methods. ‘Giant’ viruses are a recently discovered phylum of bizarre viruses with unusually large genomes. Although they're only known to infect single celled eukaryotes, they challenge our understanding of what a virus really ‘is’! The discovery aspect of this research is what I love the most about microbiology. I plan to pursue a master’s degree with the accelerated 4+1 programming microbiology here at UMass to continue my research with giant viruses. Outside the lab, I am a member of the Outing Club and I love to hike local trails in the Amherst area with my friends (my favorite is the Amethyst Brook Conservation area). I'd like to wish everyone a safe and healthy holiday! 
